sudo

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -36,12 +36,13 @@ jobs:
   
       - name: Deploy to GCP Kubernetes Cluster
         run: |
-          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
-          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
-          
-          # Atualiza a imagem no Kubernetes
+          if ! command -v gke-gcloud-auth-plugin &> /dev/null; then
+            echo "gke-gcloud-auth-plugin not found, installing..."
+            sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
+          fi
           kubectl set image deployment/${{ secrets.GCP_DEPLOYMENT_NAME }} \
-          ${{ secrets.GCP_CONTAINER_NAME }}=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest        
+          ${{ secrets.GCP_CONTAINER_NAME }}=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
+        
 
       - name: Apply Kubernetes Deployment
         run: |
